places = [{"placeName":"Grand Canyon National Park","descrip":"One of the most visited parks in America. Offers incredible views and great hikes.","latitude":36.143397,"longitude":-112.159615},
{"placeName":"Yosemite National Park","descrip":"The 2014 Yosemite Mac OS default desktop picture was taken here because of the stunning beauty of the park. ","latitude":37.844302,"longitude":-119.530541},
{"placeName":"Zion National Park","descrip":"A distinct landscape that stands out among other parks. Many famous trails are located here.","latitude":37.286508,"longitude":-113.030196},
{"placeName":"Yellowstone National Park","descrip":"Known for its interesting geological features such as mud pots, geysers, steaming vents and more. ","latitude":44.416683,"longitude":-110.610539},
{"placeName":"Sequoia & Kings Canyon National Park","descrip":"Home to some of the oldest and largest trees on the planet. Some of the trees are over 3,200 years old. ","latitude":36.564545,"longitude":-118.772693},
{"placeName":"Mammoth Cave National Park","descrip":"Experience miles and miles of gigantic caves deep underground.","latitude":37.185856,"longitude":-86.099834},
{"placeName":"Death Valley National Park","descrip":"The lowest point in the US can be found here. An unforgiving but incredible landscape.","latitude":36.75347,"longitude":-117.19405},
{"placeName":"Mesa Verde National Park","descrip":"Visit spectacular ancient archeological sites. Some of these structures are more than 700 years old.","latitude":37.221245,"longitude":-108.458936},
{"placeName":"Olympic National Park","descrip":"Composed of various terrains such as forests, beaches, and mountains,  this park offers various outdoor activities.","latitude":47.800142,"longitude":-123.604137},
{"placeName":"Canyonlands National Park","descrip":"Great for four-wheeling, hiking, and enjoying beatiful canyons. ","latitude":38.209252,"longitude":-109.925253},
{"placeName":"Redwood National and State Parks","descrip":"Home to the tallest trees in the world. Some trees are taller than 300 feet! ","latitude":41.212942,"longitude":-124.0046},
{"placeName":"Arches National Park","descrip":"Visit incredible rock formations and interesting sandstone arches carved by wind and water. ","latitude":38.732783,"longitude":-109.592525},
{"placeName":"Acadia National Park","descrip":"Full of amazing flora and fauna. See harbor seals, hawks, deers and visit the dense pine forests.","latitude":44.338512,"longitude":-68.273334},
{"placeName":"Joshua Tree National Park","descrip":"A desert landscape with fascinating rock formations. Great for hiking and climbing.  ","latitude":33.870374,"longitude":-115.90159},
{"placeName":"Bryce Canyon National Park","descrip":"Full of spectacular colors and scenic views. The park has the world's largest collection of hoodoos.","latitude":37.592161,"longitude":-112.18707},
{"placeName":"Rocky Mountain National Park","descrip":"A place for true mountain lovers. The park features 100 peaks. Great for hiking and spotting wildlife. ","latitude":40.340929,"longitude":-105.684008},
{"placeName":"Glacier National Park","descrip":"A UNESCO World Heritage Site. Features forests, mountains, and lakes. ","latitude":48.758757,"longitude":-113.788037},
{"placeName":"Big Bend National Park","descrip":"Rio Grande passes through this park. Experience mountains, canyons and historical structures. ","latitude":29.244715,"longitude":-103.249398},
{"placeName":"Great Smoky Mountains National Park","descrip":"Full of biodiversity and clear mountain streams. Enjoy hiking, fishing, cycling and camping. ","latitude":35.61106,"longitude":-83.494682},
{"placeName":"Everglades National Park","descrip":"A UNESCO World Heritage Site. Home to alligators, crocodiles and swamp lands. ","latitude":25.285612,"longitude":-80.898586}]
